name: Terraform Huawei Cloud

on:
  pull_request:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      is_approved:
        description: "Approve Terraform Apply?"
        required: true
        default: "no"
        type: choice
        options:
          - no
          - yes

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
      
    env:
      TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      TF_VAR_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_RESPONSE_CHECKSUM_VALIDATION: when_required
      AWS_REQUEST_CHECKSUM_CALCULATION: when_required

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate
        
      - name: Terraform Plan (preview)
        if: github.event_name != 'workflow_dispatch'
        run: terraform plan

      - name: Terraform Plan (manual)
        if: github.event_name == 'workflow_dispatch'
        run: terraform plan -out=tfplan
      
      - name: Test Terraform Apply condition
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "Selected approve option: ${{ github.event.inputs.is_approved }}"
          echo "Is the Terraform Plan approved? ${{ github.event.inputs.is_approved }}"

      # Apply only if manually approved during manual workflow execution
      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.is_approved
        run: terraform apply -auto-approve tfplan
